### ISSUE TITLE
Unable to run command with args via *_CHECK_CMD env vars

### ISSUE THREAD

**Issue by jf647** [progrium/docker-consul#25]
This problem is shared between docker-consul and registrator, but the simple fix would be applied to this repo.

When I try to set an env var for registrator like this:

    SERVICE_5672_CHECK_CMD=/usr/bin/rabbitmqadmin -u 'monitor' -p 'foobar' show overview

I get errors of the form in my consul logs:

    exec: "/usr/bin/rabbitmqadmin -u 'monitor' -p 'foobar' show overview": stat /usr/bin/rabbitmqadmin -u 'monitor' -p 'foobar' show overview: no such file or directory

If I emulate the command by hand by running it from the command line, I can replicate the error when putting quotes around the command:

    $ docker run --rm --net container:rabbitmq nadt.net/nadt-rabbitmq:latest "/usr/bin/rabbitmqadmin -u 'monitor' -p 'foobar' show overview"
    exec: "/usr/bin/rabbitmqadmin -u 'monitor' -p 'foobar' show overview": stat /usr/bin/rabbitmqadmin -u 'monitor' -p 'foobar' show overview: no such file or directory2014/10/06 23:01:40 Error response from daemon: Cannot start container 886bf462d44611b2a8282757f5d164c9ab8b78bf834269c6fd288833b66fea9e: exec: "/usr/bin/rabbitmqadmin -u 'monitor' -p 'foobar' show overview": stat /usr/bin/rabbitmqadmin -u 'monitor' -p 'foobar' show overview: no such file or directory

but if I leave them off, the check works:

    $ docker run --rm --net container:rabbitmq nadt.net/nadt-rabbitmq:latest /usr/bin/rabbitmqadmin -u 'monitor' -p 'foobar' show overview
    +------------------+--------------------+-----------------------+----------------------+
    | rabbitmq_version |    cluster_name    | queue_totals.messages | object_totals.queues |
    +------------------+--------------------+-----------------------+----------------------+
    | 3.3.5            | rabbit@rabbit-nadt | 0                     | 0                    |
    +------------------+--------------------+-----------------------+----------------------+

check-cmd always puts the entire command in quotes, but given that docker attempts to stat the command, I'm not sure they are serving any real purpose.  Any protection from injection attacks is easily worked around, so they just seem to stop you from even using a command with spaces in it.

Do you think the quotes in check-cmd can be safely dropped?  Am I missing something obvious that would cause that to break existing behavior?

I considered wrapping the check command into a script that I bake into an image derived from progrium/docker-consul, but then I have to bake in the creds too.  The way check-cmd is invoked, I have no mechanism to provide the creds as "check hints" in the monitored container.

I was able to work around the problem by using this env var:

    SERVICE_5672_SCRIPT=docker run --rm --net container:rabbitmq nadt.net/nadt-rabbitmq:latest /usr/bin/rabbitmqadmin -u 'monitor' -p 'foobar' show overview

But that's just noisier than it should be.

An alternate approach would be to add more hints to registrator; something like:

    SERVICE_5672_CHECK_ENV=RABBIT_USER=monitor;RABBIT_PASS=foobar

and somehow turn those into the equivalent `-e` switches passed to the `docker run` that calls check-cmd.  I'm not sure that's any better or more secure, but it definitely makes registrator's env var parsing more complex and creates an edge case around the join character - what if an env var needs to contain a semicolon, etc....

Cheers

**Comment by calvinmorrow** [comment]
+1.  Most of the nagios-style service checks require multiple arguments and there doesn't seem to be any clean way to pass them.  Even a new environment var ie $SERVICE_CHECK_ARGS as a final part to the docker command would bypass this and I believe Docker would treat it as params to the command its trying to stat.

**Comment by justinclayton** [comment]
:+1: Running something as simple as "free -m" as the check command doesn't seem to work, presumably because $@.
