### ISSUE TITLE
Docker Consul thrashing over AWS

### ISSUE THREAD

**Issue by vbichov** [progrium/docker-consul#46]
Hello,
We have tried running a consul cluster at Amazon using m3.large instances. (that allow for moderate network performance)
The machines are running RHEL 6.5 with Docker 1.3.1 using the Consul Docker image.
The 3 machines joined a cluster, yet it was completely unstable.
It kept thrashing and the state of the members was constantly shifting.
please keep in mind that this was false, since the instances of the machines and the Consul were perfectly stable and running.

We have not found any relevant documentation that would allow up to investigate and identify the cause for this.

**Comment by progrium** [comment]
Can you try the same configuration but running the Consul containers with
--net=host ?

On Thu, Jan 15, 2015 at 3:44 AM, vbichov <notifications@github.com> wrote:

> Hello,
> We have tried running a consul cluster at Amazon using m3.large instances.
> (that allow for moderate network performance)
> The machines are running RHEL 6.5 with Docker 1.3.1 using the Consul
> Docker image.
> The 3 machines joined a cluster, yet it was completely unstable.
> It kept thrashing and the state of the members was constantly shifting.
> please keep in mind that this was false, since the instances of the
> machines and the Consul were perfectly stable and running.
>
> We have not found any relevant documentation that would allow up to
> investigate and identify the cause for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/docker-consul/issues/46>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by vbichov** [comment]
Hello Progrium, thank you for the fast response.
I've only now gotten around to test it.

It looks like your solution works, i haven't run an extensive test but the system appears to be stable.
i'm closing this issue, but i would very much appreciate it, if you could please explain why it is necessary or link to any relevant documentation.
Thank you.
