### ISSUE TITLE
error when using atlas-join

### ISSUE THREAD

**Issue by oba11** [progrium/docker-consul#58]
Got this error `scada-client: failed to dial: x509: failed to load system roots and no roots provided` when trying to use `-atlas` and `-atlas-join`.
Thanks.

**Comment by progrium** [comment]
Yep, we don't support it yet. Coming soon.

On Thu, Feb 26, 2015 at 9:40 AM, Oluwaseun Obajobi <notifications@github.com
> wrote:

> Got this error scada-client: failed to dial: x509: failed to load system
> roots and no roots provided when trying to use -atlas and -atlas-join.
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/docker-consul/issues/58>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by oba11** [comment]
Oh ok, thanks alot @progrium

**Comment by oba11** [comment]
I've created a PR here https://github.com/progrium/docker-consul/pull/61 which should work.
Thanks.

**Comment by matjohn2** [comment]
@oba11 beat me to it! +1 for atlas support. Testing the PR #61 now, looks sane :)

**Comment by matjohn2** [comment]
Confirmed PR #61 looks sane and works for me.

**Comment by oba11** [comment]
Thanks @matjohn2 and @progrium for the merge
