### ISSUE TITLE
Strange DNS behaviour

### ISSUE THREAD

**Issue by ostronom** [progrium/docker-consul#59]
I'm running consul with default settings: `docker run -d -p 8400:8400 -p 8500:8500 -p 172.17.42.1:53:53/udp  -h consul progrium/consul:latest -server -bootstrap` and i have "--dns 172.17.42.1" in DOCKER_OPTS.

Then, if i issue `dig @172.17.42.1 consul.node.consul` from my host shell, i will get 
```
;; ANSWER SECTION:
consul.node.consul.     0       IN      A       172.17.0.6
```

but `docker run --rm aanand/docker-dnsutils dig consul.node.consul`

times out.

**Comment by andyshinn** [comment]
Can you confirm that the container running `aanand/docker-dnsutils` `resolv.conf` indeed has `nameserver 172.17.42.1`?

**Comment by ostronom** [comment]
Yes, it is so.

```
user@linux-mf8y:~/Work> docker run --rm -it aanand/docker-dnsutils cat /etc/resolv.conf
nameserver 172.17.42.1
```

**Comment by andyshinn** [comment]
Can you try `dig` with `+trace` and `+all` to see if it gives any additional clues? We noticed a similar issue the other day where the source IP address of the reply was from a different network (the server local IP instead of Docker bridge) and the DNS packet was rejected.

**Comment by ostronom** [comment]
I apologize, the problem was caused by default openSUSE firewall configuration. If i turn it off -- everything works perfectly well.
