### ISSUE TITLE
Support changing consul domain

### ISSUE THREAD

**Issue by discordianfish** [progrium/docker-consul#62]
Hi,

I want to change the consul domain which isn't possible with this docker image.
I'm happy to contribute the necessary changes, just let me know if you have some ideas how.
I would probably modify the json as part of the run script or something..?

**Comment by progrium** [comment]
What makes you think it's not possible? What have you tried?

On Wed, Mar 11, 2015 at 2:44 PM, discordianfish <notifications@github.com>
wrote:

> Hi,
>
> I want to change the consul domain which isn't possible with this docker
> image.
> I'm happy to contribute the necessary changes, just let me know if you
> have some ideas how.
> I would probably modify the json as part of the run script or something..?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/docker-consul/issues/62>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by discordianfish** [comment]
Well it requires changes to config/consul.json which isn't possible by just passing env variables or parameters to the container. Sure, I can create a image using yours as base image, but given that the domain is a pretty common option to change (at least I assume), it would be good to have support for that in your image. But if you disagree, I'll just go that route and you can close the issue.

**Comment by thpham** [comment]
I also need to change the domain, but as @discordianfish said, it's impossible to start the server with -domain argument, the only way it to have it through consul.json

+1 for this feature please, thanks

**Comment by discordianfish** [comment]
I've just opened this PR to solve this in consul itself: https://github.com/hashicorp/consul/pull/805

**Comment by joshskinner** [comment]
I just ran into this as well.  Interesting that the consul config is disconnected in features from the command line.  Nice job getting it in @discordianfish!  Looking forward to the next release of Consul so we can utilize this feature.  Thanks also to @progrium to putting this together in the first place!

**Comment by ankushagarwal** [comment]
Is this still a problem? I was able to add the `-domain mydomain.com` option during `docker run` and it worked

**Comment by discordianfish** [comment]
Yes, I think this is fixed with the current consul version in the image.
