### ISSUE TITLE
How to run check-http health checks

### ISSUE THREAD

**Issue by johnjelinek** [progrium/docker-consul#64]
I tried adding a health check via the HTTP API (is there another way?).
```
curl -XPUT -d '{"Name": "test", "Check": { "script": "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --entrypoint /bin/bash progrium/consul check-http e1d219c59ded 2368 / -L", "interval": "10s" }}' http://127.0.0.1:8500/v1/agent/service/register -v
```

Here's the result:
```
time="2015-03-29T04:02:14Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.17/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?" 
```

**Comment by johnjelinek** [comment]
If I start the container mounting `-v /var/run/docker.sock:/var/run/docker.sock`, it dies immediately. The logs only say this:
```
$ docker logs -f consul
Consul v0.5.0
Consul Protocol: 2 (Understands back to: 1)
```

**Comment by progrium** [comment]
You should not be calling Docker in your health script. It's already running in that container, no need to start a new one from inside it. 

The second issue seems unrelated, but if you learn more let me know.

**Comment by johnjelinek** [comment]
so, learning points for me -- the IP I `PUT` to is the consul agent that executes the check. So, it makes sense that my check should actually be something like this:
```
curl -XPUT -d '{"Name": "test", "Check": { "script": "check-http e1d219c59ded 2368 / -L", "interval": "10s" }}' http://127.0.0.1:8500/v1/agent/service/register -v
```

But even with this, it means I needed to start my local consul container with `-v /var/run/docker.sock:/var/run/docker.sock`, which makes the container die immediately with the output I mentioned previously. So if I execute the `PUT` I mentioned here, it still results with the error message:
```
time="2015-03-29T04:02:14Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.17/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?" 
```

**Comment by johnjelinek** [comment]
Ok, so, I finally got `docker.sock` mounted, but when I do:
```
curl -XPUT -d '{"Name": "test", "Check": { "script": "check-http e1d219c59ded 2368 / -L", "interval": "10s" }}' http://127.0.0.1:8500/v1/agent/service/register -v
```
it adds the check in consul, but I don't see it listed under checks in consul, only under services.

**Comment by johnjelinek** [comment]
I had to deregister first before re-registering the service. Is there another recommended way to add a service health check other than the HTTP API?

**Comment by johnjelinek** [comment]
strange, I'm getting passes and fails from running check-http. Here's an example of a fail:
```
HTTP/1.1 301 Moved Permanently
X-Powered-By: Express
Location: https://www.beaneighbor.org/
Vary: Accept, Accept-Encoding
Content-Type: text/plain; charset=utf-8
Content-Length: 62
Date: Tue, 31 Mar 2015 04:11:06 GMT
Connection: keep-alive

HTTP/1.1 200 OK
Server: nginx/1.7.10
Date: Tue, 31 Mar 2015 04:11:06 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 3614
Connection: keep-alive
X-Powered-By: Express
Cache-Control: public, max-age=0
ETag: W/"eNI8enDoQrRPnnvUdAtWbw=="
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000

time="2015-03-31T04:11:06Z" level="fatal" msg="Error response from daemon: Cannot destroy container 10c6a50d8c042eff041404025a3560c53f881366d5426a9dc84a05a036036004: Driver aufs failed to remove root filesystem 10c6a50d8c042eff041404025a3560c53f881366d5426a9dc84a05a036036004: rename /var/lib/docker/aufs/mnt/10c6a50d8c042eff041404025a3560c53f881366d5426a9dc84a05a036036004 /var/lib/docker/aufs/mnt/10c6a50d8c042eff041404025a3560c53f881366d5426a9dc84a05a036036004-removing: device or resource busy" 
```
When it passes, it leaves off that last section. Any thoughts?

**Comment by progrium** [comment]
That is an error from Docker not the check.

On Mon, Mar 30, 2015 at 11:13 PM, John Jelinek IV <notifications@github.com>
wrote:

> strange, I'm getting passes and fails from running check-http. Here's an
> example of a fail:
>
> HTTP/1.1 301 Moved Permanently
> X-Powered-By: Express
> Location: https://www.beaneighbor.org/
> Vary: Accept, Accept-Encoding
> Content-Type: text/plain; charset=utf-8
> Content-Length: 62
> Date: Tue, 31 Mar 2015 04:11:06 GMT
> Connection: keep-alive
>
> HTTP/1.1 200 OK
> Server: nginx/1.7.10
> Date: Tue, 31 Mar 2015 04:11:06 GMT
> Content-Type: text/html; charset=utf-8
> Content-Length: 3614
> Connection: keep-alive
> X-Powered-By: Express
> Cache-Control: public, max-age=0
> ETag: W/"eNI8enDoQrRPnnvUdAtWbw=="
> Vary: Accept-Encoding
> Strict-Transport-Security: max-age=31536000
>
> time="2015-03-31T04:11:06Z" level="fatal" msg="Error response from daemon: Cannot destroy container 10c6a50d8c042eff041404025a3560c53f881366d5426a9dc84a05a036036004: Driver aufs failed to remove root filesystem 10c6a50d8c042eff041404025a3560c53f881366d5426a9dc84a05a036036004: rename /var/lib/docker/aufs/mnt/10c6a50d8c042eff041404025a3560c53f881366d5426a9dc84a05a036036004 /var/lib/docker/aufs/mnt/10c6a50d8c042eff041404025a3560c53f881366d5426a9dc84a05a036036004-removing: device or resource busy"
>
> When it passes, it leaves off that last section. Any thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/docker-consul/issues/64#issuecomment-87928986>
> .
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by johnjelinek** [comment]
I wonder why an error message from docker would display at the end of the http check.

**Comment by progrium** [comment]
Because it uses Docker: https://github.com/progrium/docker-consul/blob/master/check-http#L20

**Comment by johnjelinek** [comment]
:laughing: got it. So the container failed to delete, I guess.
