### ISSUE TITLE
How to do health checks on host node?

### ISSUE THREAD

**Issue by johnjelinek** [progrium/docker-consul#67]
If I wanted to create a script to do memory usage or `pgrep` to make sure something was running on the node, how would I do that here?

**Comment by progrium** [comment]
You need to work with Docker semantics to be able to do that from within
the Consul container. Easiest answer is: don't. Focus service checks on
network checks.

On Sun, Mar 29, 2015 at 3:52 PM, John Jelinek IV <notifications@github.com>
wrote:

> If I wanted to create a script to do memory usage or pgrep to make sure
> something was running on the node, how would I do that here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/docker-consul/issues/67>.
>



-- 
Jeff Lindsay
http://progrium.com
