### ISSUE TITLE
Consul leave cluster = Docker exit 255

### ISSUE THREAD

**Issue by JeanMertz** [progrium/docker-consul#72]
I have a cluster of several nodes running Consul. The cluster has the consul "client" agent running on all nodes. These client agents stop when they detect a server agent booting up on the machine.

Right now, I have the "stop" command (in Systemd) to be `docker exec consul-client consul leave`. This way, the agents leave the cluster gracefully, without showing up as `failed`.

However, since Consul is PID 1 in the Docker container, this means Docker automatically stops (no problem there), but also returns exit code `255`.

I can let Systemd *know* that this is a valid exit code, but of course it's not always valid, if Consul ever crashes, 255 would be an invalid exit code.

Any thoughts on how to best handle this use-case?

**Comment by JeanMertz** [comment]
I'm closing this, after some more testing it seems `leave` actually exits the Docker container with 0 status, so something else is going on here.

**Comment by progrium** [comment]
`SIGTERM` should also trigger graceful leave if `leave_on_terminate` is configured. Not sure what's going on with the exit code, but this might simplify things.

**Comment by JeanMertz** [comment]
thanks @progrium, just what the doctor ordered.

Also, this might be worth considering: https://github.com/progrium/docker-consul/issues/34
