### ISSUE TITLE
Consul CLI

### ISSUE THREAD

**Issue by laktak** [progrium/docker-consul#73]
When I want to use the cli I run:
```
docker run --rm -e CONSUL_RPC_ADDR=addr:8400 -ti --entrypoint /bin/bash progrium/consul
```

Then I can run `consul members`. 

Is there an easier way or could you support this in your start script?

**Comment by cgswong** [comment]
@laktak `docker exec [container_name | ID] consul members`

**Comment by laktak** [comment]
Great, thanks!
