### ISSUE TITLE
AWS production cluster gets i/o timeout on -join

### ISSUE THREAD

**Issue by Stellaverse** [progrium/docker-consul#93]
Hey Jeff,

Thanks for all the excellent work you do. `docker-consul` and `registrator` are quickly becoming essential parts of my system; once I can get them to talk to each other, that is.

I've followed the [Running a real consul cluster in production] (https://github.com/progrium/docker-consul#running-a-real-consul-cluster-in-a-production-environment) instructions but I'm getting an `i/o timeout` error when my `consul2` and `consul3` nodes attempt to `-join` the `consul1` private IP.

I spun up three `t2.micros` on AWS and got the following Private IP's assigned in my VPC:
```
172.31.4.194 (Intended to be `consul1`, leader)
172.31.4.195 (Intended to be `consul2`)
172.31.4.193 (Intended to be `consul3`)
```

My `consul1` node gets itself up and waiting for the other two just fine:
```
sudo docker run -d -h consul1 --name consul1 -v /mnt:/data \
    -p 172.31.4.194:8300:8300 \
    -p 172.31.4.194:8301:8301 \
    -p 172.31.4.194:8301:8301/udp \
    -p 172.31.4.194:8302:8302 \
    -p 172.31.4.194:8302:8302/udp \
    -p 172.31.4.194:8400:8400 \
    -p 172.31.4.194:8500:8500 \
    -p 172.17.42.1:53:53/udp \
    progrium/consul -server -advertise 172.31.4.194-bootstrap-expect 3
```

But then when I attempt to start my `consul2` node, using the following:
```
sudo docker run -d -h consul2 --name consul2 -v /mnt:/data \
    -p 172.31.4.195:8300:8300 \
    -p 172.31.4.195:8301:8301 \
    -p 172.31.4.195:8301:8301/udp \
    -p 172.31.4.195:8302:8302 \
    -p 172.31.4.195:8302:8302/udp \
    -p 172.31.4.195:8400:8400 \
    -p 172.31.4.195:8500:8500 \
    -p 172.17.42.1:53:53/udp \
    progrium/consul -server -advertise 172.31.4.195 -join 172.31.4.194
```

Here's the error that I'm getting:
```
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting raft data migration...
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Joining cluster...
==> dial tcp 172.31.4.194:8301: i/o timeout
```

In the above, `172.31.4.194` is the private IP that AWS assigned to my `consul1` instance (intended to be the leader).

Any idea of what could be causing this? I've re-attempted about nine times and still no luck. It did spur me to do some more learning about networking (which is a broad, deep, fascinating subject) but I can't figure out if there's an issue in my config, or if this is an actual bug.

Thanks in advance for any help.

**Comment by Stellaverse** [comment]
Nevermind! Figure it out.

I had to open up some ports in the security group that governs access to my Consul1,2,3 instances. I opened up: 8300, 8301, 8302, 8400, and 8500.

Not sure if all of them need to be open. Playing with that now.

**Comment by jmvbxx** [comment]
Can you tell me what your original security group settings were?

Right now I've got all TCP traffic open for incoming and all traffic open for outgoing and I'm still having this problem.

Thanks!
